import type { Rate, Shop, District, Comment } from './types'

const now = new Date().toISOString()

export const rates: Rate[] = [
  {
    id: 'gold-18',
    name: 'طلای ۱۸ عیار (هر گرم)',
    price: 38450000,
    changePercent: 1.24,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'gold-24',
    name: 'طلای ۲۴ عیار (هر گرم)',
    price: 51260000,
    changePercent: 1.18,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'mesghal',
    name: 'مثقال طلا',
    price: 166700000,
    changePercent: 0.94,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'coin-emami',
    name: 'سکه امامی',
    price: 4185000000,
    changePercent: -0.42,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'coin-bahar',
    name: 'سکه بهار آزادی',
    price: 3920000000,
    changePercent: -0.31,
    source: 'manual',
    updatedAt: now,
  },
  {
    id: 'coin-half',
    name: 'نیم سکه',
    price: 2210000000,
    changePercent: 0.15,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'coin-quarter',
    name: 'ربع سکه',
    price: 1380000000,
    changePercent: 0.62,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'usd',
    name: 'دلار آمریکا',
    price: 1062000,
    changePercent: 0.38,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'eur',
    name: 'یورو',
    price: 1148000,
    changePercent: -0.21,
    source: 'api',
    updatedAt: now,
  },
  {
    id: 'aed',
    name: 'درهم امارات',
    price: 289500,
    changePercent: 0.44,
    source: 'manual',
    updatedAt: now,
  },
]

export const districts: District[] = [
  { id: 'd1', name: 'حرم مطهر', slug: 'haram', lat: 36.2877, lng: 59.6157 },
  { id: 'd2', name: 'احمدآباد', slug: 'ahmadabad', lat: 36.2972, lng: 59.6067 },
  { id: 'd3', name: 'سجاد', slug: 'sajjad', lat: 36.3145, lng: 59.5642 },
  { id: 'd4', name: 'وکیل‌آباد', slug: 'vakilabad', lat: 36.3265, lng: 59.5085 },
  { id: 'd5', name: 'طبرسی', slug: 'tabarsi', lat: 36.3041, lng: 59.6342 },
  { id: 'd6', name: 'بازار رضا', slug: 'bazar-reza', lat: 36.2901, lng: 59.6098 },
]

export const shops: Shop[] = [
  {
    id: 's1',
    name: 'طلا و جواهر زرین',
    address: 'مشهد، خیابان امام رضا، نبش امام رضا ۸',
    phone: '۰۵۱-۳۲۲۱۴۴۵۶',
    workingHours: '۹:۰۰ تا ۲۱:۰۰',
    lat: 36.2885,
    lng: 59.6132,
    district: 'حرم مطهر',
    rating: 4.8,
    imageUrl: '/shop-zarin.png',
  },
  {
    id: 's2',
    name: 'گالری طلای پارسیان',
    address: 'مشهد، احمدآباد، خیابان عدالت، پلاک ۴۵',
    phone: '۰۵۱-۳۸۴۵۷۸۹۰',
    workingHours: '۱۰:۰۰ تا ۲۲:۰۰',
    lat: 36.2988,
    lng: 59.6041,
    district: 'احمدآباد',
    rating: 4.6,
    imageUrl: '/shop-parsian.png',
  },
  {
    id: 's3',
    name: 'طلافروشی آریا',
    address: 'مشهد، بلوار سجاد، نبش سجاد ۱۲',
    phone: '۰۵۱-۳۷۶۲۳۳۴۵',
    workingHours: '۹:۳۰ تا ۲۰:۳۰',
    lat: 36.3158,
    lng: 59.5668,
    district: 'سجاد',
    rating: 4.9,
    imageUrl: '/shop-aria.png',
  },
  {
    id: 's4',
    name: 'جواهری الماس شرق',
    address: 'مشهد، بلوار وکیل‌آباد، بین وکیل‌آباد ۱۰ و ۱۲',
    phone: '۰۵۱-۳۸۶۷۱۱۲۲',
    workingHours: '۱۰:۰۰ تا ۲۱:۰۰',
    lat: 36.3271,
    lng: 59.5102,
    district: 'وکیل‌آباد',
    rating: 4.4,
    imageUrl: '/shop-almas.png',
  },
  {
    id: 's5',
    name: 'طلا و جواهر کیمیا',
    address: 'مشهد، خیابان طبرسی، نرسیده به فلکه آب',
    phone: '۰۵۱-۳۲۷۳۸۸۹۹',
    workingHours: '۸:۳۰ تا ۲۰:۰۰',
    lat: 36.3055,
    lng: 59.6358,
    district: 'طبرسی',
    rating: 4.2,
    imageUrl: '/shop-kimia.png',
  },
  {
    id: 's6',
    name: 'گالری طلای شاهان',
    address: 'مشهد، بازار رضا، راسته طلافروشان، پلاک ۲۳',
    phone: '۰۵۱-۳۲۲۳۴۵۶۷',
    workingHours: '۹:۰۰ تا ۲۰:۳۰',
    lat: 36.2912,
    lng: 59.6085,
    district: 'بازار رضا',
    rating: 4.7,
    imageUrl: '/shop-shahan.png',
  },
  {
    id: 's7',
    name: 'طلافروشی صدف',
    address: 'مشهد، احمدآباد، خیابان پاستور، پلاک ۸',
    phone: '۰۵۱-۳۸۴۱۲۳۴۵',
    workingHours: '۱۰:۰۰ تا ۲۱:۳۰',
    lat: 36.2961,
    lng: 59.6089,
    district: 'احمدآباد',
    rating: 4.5,
    imageUrl: '/shop-sadaf.png',
  },
  {
    id: 's8',
    name: 'جواهری نگین طلایی',
    address: 'مشهد، بلوار سجاد، خیابان بهارستان، پلاک ۱۹',
    phone: '۰۵۱-۳۷۶۸۹۹۰۰',
    workingHours: '۹:۰۰ تا ۲۱:۰۰',
    lat: 36.3132,
    lng: 59.5601,
    district: 'سجاد',
    rating: 4.3,
    imageUrl: '/shop-negin.png',
  },
]

export const comments: Comment[] = [
  {
    id: 'c1',
    shopId: 's1',
    userName: 'علی محمدی',
    rating: 5,
    text: 'برخورد بسیار حرفه‌ای و قیمت‌های منصفانه. حتماً دوباره مراجعه می‌کنم.',
    status: 'pending',
    createdAt: now,
  },
  {
    id: 'c2',
    shopId: 's3',
    userName: 'مریم احمدی',
    rating: 4,
    text: 'تنوع محصولات خوب بود ولی کمی شلوغ بود.',
    status: 'pending',
    createdAt: now,
  },
  {
    id: 'c3',
    shopId: 's2',
    userName: 'حسین رضایی',
    rating: 5,
    text: 'کیفیت ساخت طلاها عالی بود و مشاوره خوبی دریافت کردم.',
    status: 'approved',
    createdAt: now,
  },
  {
    id: 'c4',
    shopId: 's6',
    userName: 'زهرا کریمی',
    rating: 3,
    text: 'قیمت‌ها نسبت به جاهای دیگر کمی بالاتر بود.',
    status: 'pending',
    createdAt: now,
  },
  {
    id: 'c5',
    shopId: 's5',
    userName: 'محمد حسینی',
    rating: 4,
    text: 'فروشگاه تمیز و مرتبی داشتند، راضی بودم.',
    status: 'rejected',
    createdAt: now,
  },
]
